title: Ingeros # Your site's title
tagline: Innovación tecnológica # A short description, used as part of the title
description: Somos una empresa localizada en Rosario, enfocada en brindar soluciones basadas en el diseño y desarrollo de hardware y/o software, en áreas como electrónica, automatismo, domótica, adquisición de datos, sistemas de supervisión, automatización industrial, control de procesos. Garantizamos productos confiables desarrollados con tecnologías de hardware y software libre. 
url: test-ariel.github.io # The full URL to your site.
author: arielsperduti

logo: # URL to a site-wide logo, 

twitter:
  username: arielsperduti # The site's Twitter handle. It not necessarily the same as the author
  card: suummary # The site's default card type

facebook:
  app_id: # Facebook app ID for Facebook insights
  publisher: # Facebook page URL or ID of the publishing entity
  admins: # Facebook user ID for domain insights linked to a personal account

social: # For specifyng social profiles
  name: Ingeros
  links:
    - https://facebook.com/ingeros.argentina
    - https://www.linkedin.com/company/ingeros/
    - https://github.com/ingeros
    - https://instagram.com/ingeros.arg

webmaster_verifications: # Verify ownership with several services at
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

lang:  es_AR # Locale tag follow the format language_TERRITORY

#theme: jekyll-theme-pancho

# sass
sass:
  style: :compressed

plugins:
  - jekyll-purgecss
  - jekyll-seo-tag
  - jekyll-redirect-from

css_dir: "assets/css" # defaults to "css"

exclude: 
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - Makefile
  - README.md
  - package-lock.json
  - package.json
  - pancho.gemspec
  - purgecss.config.js

include:
  - _pages